### ISSUE TITLE
'make' creates rom, unbootable in Fusion or on real hardware

### ISSUE THREAD

**Issue by douggie12** [andwn/ym2017#2]
installing marsdev in Ubuntu with 'make' command, and following that with 'make' ym2017 yields a ym2017.bin that is unplayable

in the build log I receive multiple errors like:

AS src/xgm/z80_xgm.s
src/xgm/z80_xgm.s: Assembler messages:
src/xgm/z80_xgm.s:7: Warning: value 0xfffffff331 truncated to 0xf331
src/xgm/z80_xgm.s:7: Warning: value 0xffffffed56 truncated to 0xed56
src/xgm/z80_xgm.s:7: Warning: value 0xffffffaf32 truncated to 0xaf32

as well as : 

src/vdp_tile.c:44:9: warning: implicit declaration of function 'lz4w_unpack' [-Wimplicit-function-declaration]
         lz4w_unpack((uint8_t*) src->tiles, (uint8_t*) result->tiles);
         ^~~~~~~~~~~

Upon booting .bin in fusion I get checksum error

**Comment by andwn** [comment]
I think we're going to need to see the full make log. Most of those errors happen when it works.

For example, Java is required by the lz4w compressor but newer versions of rescomp don't error out if it is missing (this wasn't the case when ym2017 was released). It'll show a message like this:

    Executing java -jar /Users/Cirno/mars/bin/lz4w.jar p "pack.in" "pack.out" -s
    No Java runtime present, requesting install.
    No compression, original size = 38400 compressed to 38400 (100 %)

But you want to see this:

    Executing java -jar /Users/Cirno/mars/bin/lz4w.jar p "pack.in" "pack.out" -s
    Packed with LZ4W, original size = 38400 compressed to 13780 (35.8854 %)

**Comment by andwn** [comment]
Well, may as well fix the warning about lz4w_unpack since I had to fix the dd command for OS X.

The biggest mystery to me is the truncation warnings for xgm_z80.s. I'm not getting those and they are certainly a bad sign when they show up. Perhaps one of the marsdev dependencies changed something, namely sjasm. When I have some extra time this week I'll rebuild marsdev and see what happens.

**Comment by andwn** [comment]
Old
