### ISSUE TITLE
Support wide screen

### ISSUE THREAD

**Issue by xmha97** [andwn/ym2017#5]
Hi, please support wide screen
![image](https://user-images.githubusercontent.com/23485114/155199310-e866d973-3731-451e-987a-7425e903db1f.png)
Like Cave Story
![image](https://user-images.githubusercontent.com/23485114/155199427-9c0ed139-0a68-4c54-b4ad-f9812d1c9ae7.png)

**Comment by andwn** [comment]
Genesis is not wide screen. This is probably some kind of emulator feature you are using. I will not support it.
